name: trump-truth-social-archive (no S3)

on:
  workflow_dispatch:
  schedule:
    - cron: '47 */4 * * *'  # every 4 hours at :47

permissions:
  contents: write  # needed so the workflow can push commits

concurrency:
  group: trump-truth-archive
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          SCRAPE_PROXY_KEY: ${{ secrets.SCRAPE_PROXY_KEY }}
        run: |
          set -e
          python scrape.py

      # Commit any changed files (e.g., data/**, truth_archive.*) back to the repo
      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Truth Social archive (no S3)"
          # omit file_pattern to commit all changes that the scraper made
